namespace exelScraper
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.dataGridView = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.correlationCoefficientBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.covButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.columnDropDown2 = new Bunifu.UI.WinForms.BunifuDropdown();
            this.bunifuSeparator2 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.standardDeviationBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.varianceBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.quantileButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.rangeButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.columnDropDown = new Bunifu.UI.WinForms.BunifuDropdown();
            this.bunifuSeparator1 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.avrageButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView)).BeginInit();
            this.bunifuPanel1.SuspendLayout();
            this.bunifuPanel2.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Get Exel";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges1;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.Empty;
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.Empty;
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI Semibold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton1.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.IconLeft = null;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRight = null;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton1.IdleBorderRadius = 0;
            this.bunifuButton1.IdleBorderThickness = 0;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.Empty;
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(12, 12);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 1;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.IndianRed;
            this.bunifuButton1.onHoverState.BorderRadius = 1;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton1.OnIdleState.BorderRadius = 1;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnIdleState.IconLeftImage = null;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.BorderRadius = 1;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(185, 39);
            this.bunifuButton1.TabIndex = 0;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            this.bunifuButton1.Click += new System.EventHandler(this.buttonGetFile_Click);
            // 
            // dataGridView
            // 
            this.dataGridView.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.dataGridView.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dataGridView.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.dataGridView.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dataGridView.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dataGridView.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dataGridView.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dataGridView.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dataGridView.ColumnHeadersHeight = 40;
            this.dataGridView.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dataGridView.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dataGridView.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dataGridView.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dataGridView.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dataGridView.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dataGridView.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dataGridView.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.dataGridView.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dataGridView.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dataGridView.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.dataGridView.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dataGridView.CurrentTheme.Name = null;
            this.dataGridView.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dataGridView.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dataGridView.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dataGridView.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dataGridView.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dataGridView.DefaultCellStyle = dataGridViewCellStyle3;
            this.dataGridView.EnableHeadersVisualStyles = false;
            this.dataGridView.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dataGridView.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.dataGridView.HeaderBgColor = System.Drawing.Color.Empty;
            this.dataGridView.HeaderForeColor = System.Drawing.Color.White;
            this.dataGridView.Location = new System.Drawing.Point(203, 0);
            this.dataGridView.Name = "dataGridView";
            this.dataGridView.RowHeadersVisible = false;
            this.dataGridView.RowTemplate.Height = 40;
            this.dataGridView.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dataGridView.Size = new System.Drawing.Size(1024, 715);
            this.dataGridView.TabIndex = 4;
            this.dataGridView.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.SteelBlue;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.correlationCoefficientBtn);
            this.bunifuPanel1.Controls.Add(this.covButton);
            this.bunifuPanel1.Controls.Add(this.columnDropDown2);
            this.bunifuPanel1.Controls.Add(this.bunifuSeparator2);
            this.bunifuPanel1.Controls.Add(this.standardDeviationBtn);
            this.bunifuPanel1.Controls.Add(this.varianceBtn);
            this.bunifuPanel1.Controls.Add(this.quantileButton);
            this.bunifuPanel1.Controls.Add(this.rangeButton);
            this.bunifuPanel1.Controls.Add(this.columnDropDown);
            this.bunifuPanel1.Controls.Add(this.bunifuSeparator1);
            this.bunifuPanel1.Controls.Add(this.avrageButton);
            this.bunifuPanel1.Controls.Add(this.bunifuPanel2);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(208, 715);
            this.bunifuPanel1.TabIndex = 5;
            // 
            // correlationCoefficientBtn
            // 
            this.correlationCoefficientBtn.AllowAnimations = true;
            this.correlationCoefficientBtn.AllowMouseEffects = true;
            this.correlationCoefficientBtn.AllowToggling = false;
            this.correlationCoefficientBtn.AnimationSpeed = 200;
            this.correlationCoefficientBtn.AutoGenerateColors = false;
            this.correlationCoefficientBtn.AutoRoundBorders = false;
            this.correlationCoefficientBtn.AutoSizeLeftIcon = true;
            this.correlationCoefficientBtn.AutoSizeRightIcon = true;
            this.correlationCoefficientBtn.BackColor = System.Drawing.Color.Transparent;
            this.correlationCoefficientBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.correlationCoefficientBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("correlationCoefficientBtn.BackgroundImage")));
            this.correlationCoefficientBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.correlationCoefficientBtn.ButtonText = "Correlation coefficient";
            this.correlationCoefficientBtn.ButtonTextMarginLeft = 0;
            this.correlationCoefficientBtn.ColorContrastOnClick = 45;
            this.correlationCoefficientBtn.ColorContrastOnHover = 45;
            this.correlationCoefficientBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.correlationCoefficientBtn.CustomizableEdges = borderEdges2;
            this.correlationCoefficientBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.correlationCoefficientBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.correlationCoefficientBtn.DisabledFillColor = System.Drawing.Color.Empty;
            this.correlationCoefficientBtn.DisabledForecolor = System.Drawing.Color.Empty;
            this.correlationCoefficientBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.correlationCoefficientBtn.Font = new System.Drawing.Font("Segoe UI Semibold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.correlationCoefficientBtn.ForeColor = System.Drawing.Color.White;
            this.correlationCoefficientBtn.IconLeft = null;
            this.correlationCoefficientBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.correlationCoefficientBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.correlationCoefficientBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.correlationCoefficientBtn.IconMarginLeft = 11;
            this.correlationCoefficientBtn.IconPadding = 10;
            this.correlationCoefficientBtn.IconRight = null;
            this.correlationCoefficientBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.correlationCoefficientBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.correlationCoefficientBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.correlationCoefficientBtn.IconSize = 25;
            this.correlationCoefficientBtn.IdleBorderColor = System.Drawing.Color.Empty;
            this.correlationCoefficientBtn.IdleBorderRadius = 0;
            this.correlationCoefficientBtn.IdleBorderThickness = 0;
            this.correlationCoefficientBtn.IdleFillColor = System.Drawing.Color.Empty;
            this.correlationCoefficientBtn.IdleIconLeftImage = null;
            this.correlationCoefficientBtn.IdleIconRightImage = null;
            this.correlationCoefficientBtn.IndicateFocus = false;
            this.correlationCoefficientBtn.Location = new System.Drawing.Point(12, 453);
            this.correlationCoefficientBtn.Name = "correlationCoefficientBtn";
            this.correlationCoefficientBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.correlationCoefficientBtn.OnDisabledState.BorderRadius = 1;
            this.correlationCoefficientBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.correlationCoefficientBtn.OnDisabledState.BorderThickness = 1;
            this.correlationCoefficientBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.correlationCoefficientBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.correlationCoefficientBtn.OnDisabledState.IconLeftImage = null;
            this.correlationCoefficientBtn.OnDisabledState.IconRightImage = null;
            this.correlationCoefficientBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.correlationCoefficientBtn.onHoverState.BorderRadius = 1;
            this.correlationCoefficientBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.correlationCoefficientBtn.onHoverState.BorderThickness = 1;
            this.correlationCoefficientBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.correlationCoefficientBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.correlationCoefficientBtn.onHoverState.IconLeftImage = null;
            this.correlationCoefficientBtn.onHoverState.IconRightImage = null;
            this.correlationCoefficientBtn.OnIdleState.BorderColor = System.Drawing.Color.Orange;
            this.correlationCoefficientBtn.OnIdleState.BorderRadius = 1;
            this.correlationCoefficientBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.correlationCoefficientBtn.OnIdleState.BorderThickness = 1;
            this.correlationCoefficientBtn.OnIdleState.FillColor = System.Drawing.Color.Orange;
            this.correlationCoefficientBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.correlationCoefficientBtn.OnIdleState.IconLeftImage = null;
            this.correlationCoefficientBtn.OnIdleState.IconRightImage = null;
            this.correlationCoefficientBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.correlationCoefficientBtn.OnPressedState.BorderRadius = 1;
            this.correlationCoefficientBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.correlationCoefficientBtn.OnPressedState.BorderThickness = 1;
            this.correlationCoefficientBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.correlationCoefficientBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.correlationCoefficientBtn.OnPressedState.IconLeftImage = null;
            this.correlationCoefficientBtn.OnPressedState.IconRightImage = null;
            this.correlationCoefficientBtn.Size = new System.Drawing.Size(185, 39);
            this.correlationCoefficientBtn.TabIndex = 16;
            this.correlationCoefficientBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.correlationCoefficientBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.correlationCoefficientBtn.TextMarginLeft = 0;
            this.correlationCoefficientBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.correlationCoefficientBtn.UseDefaultRadiusAndThickness = true;
            this.correlationCoefficientBtn.Click += new System.EventHandler(this.correlationCoefficientBtn_Click);
            // 
            // covButton
            // 
            this.covButton.AllowAnimations = true;
            this.covButton.AllowMouseEffects = true;
            this.covButton.AllowToggling = false;
            this.covButton.AnimationSpeed = 200;
            this.covButton.AutoGenerateColors = false;
            this.covButton.AutoRoundBorders = false;
            this.covButton.AutoSizeLeftIcon = true;
            this.covButton.AutoSizeRightIcon = true;
            this.covButton.BackColor = System.Drawing.Color.Transparent;
            this.covButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.covButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("covButton.BackgroundImage")));
            this.covButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.covButton.ButtonText = "Covariance";
            this.covButton.ButtonTextMarginLeft = 0;
            this.covButton.ColorContrastOnClick = 45;
            this.covButton.ColorContrastOnHover = 45;
            this.covButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.covButton.CustomizableEdges = borderEdges3;
            this.covButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.covButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.covButton.DisabledFillColor = System.Drawing.Color.Empty;
            this.covButton.DisabledForecolor = System.Drawing.Color.Empty;
            this.covButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.covButton.Font = new System.Drawing.Font("Segoe UI Semibold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.covButton.ForeColor = System.Drawing.Color.White;
            this.covButton.IconLeft = null;
            this.covButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.covButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.covButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.covButton.IconMarginLeft = 11;
            this.covButton.IconPadding = 10;
            this.covButton.IconRight = null;
            this.covButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.covButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.covButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.covButton.IconSize = 25;
            this.covButton.IdleBorderColor = System.Drawing.Color.Empty;
            this.covButton.IdleBorderRadius = 0;
            this.covButton.IdleBorderThickness = 0;
            this.covButton.IdleFillColor = System.Drawing.Color.Empty;
            this.covButton.IdleIconLeftImage = null;
            this.covButton.IdleIconRightImage = null;
            this.covButton.IndicateFocus = false;
            this.covButton.Location = new System.Drawing.Point(12, 408);
            this.covButton.Name = "covButton";
            this.covButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.covButton.OnDisabledState.BorderRadius = 1;
            this.covButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.covButton.OnDisabledState.BorderThickness = 1;
            this.covButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.covButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.covButton.OnDisabledState.IconLeftImage = null;
            this.covButton.OnDisabledState.IconRightImage = null;
            this.covButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.covButton.onHoverState.BorderRadius = 1;
            this.covButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.covButton.onHoverState.BorderThickness = 1;
            this.covButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.covButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.covButton.onHoverState.IconLeftImage = null;
            this.covButton.onHoverState.IconRightImage = null;
            this.covButton.OnIdleState.BorderColor = System.Drawing.Color.Orange;
            this.covButton.OnIdleState.BorderRadius = 1;
            this.covButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.covButton.OnIdleState.BorderThickness = 1;
            this.covButton.OnIdleState.FillColor = System.Drawing.Color.Orange;
            this.covButton.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.covButton.OnIdleState.IconLeftImage = null;
            this.covButton.OnIdleState.IconRightImage = null;
            this.covButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.covButton.OnPressedState.BorderRadius = 1;
            this.covButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.covButton.OnPressedState.BorderThickness = 1;
            this.covButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.covButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.covButton.OnPressedState.IconLeftImage = null;
            this.covButton.OnPressedState.IconRightImage = null;
            this.covButton.Size = new System.Drawing.Size(185, 39);
            this.covButton.TabIndex = 15;
            this.covButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.covButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.covButton.TextMarginLeft = 0;
            this.covButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.covButton.UseDefaultRadiusAndThickness = true;
            this.covButton.Click += new System.EventHandler(this.covButton_Click);
            // 
            // columnDropDown2
            // 
            this.columnDropDown2.BackColor = System.Drawing.Color.Transparent;
            this.columnDropDown2.BackgroundColor = System.Drawing.Color.White;
            this.columnDropDown2.BorderColor = System.Drawing.Color.Silver;
            this.columnDropDown2.BorderRadius = 1;
            this.columnDropDown2.Color = System.Drawing.Color.Silver;
            this.columnDropDown2.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.columnDropDown2.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.columnDropDown2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.columnDropDown2.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.columnDropDown2.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.columnDropDown2.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.columnDropDown2.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.columnDropDown2.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.columnDropDown2.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.columnDropDown2.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.columnDropDown2.FillDropDown = true;
            this.columnDropDown2.FillIndicator = false;
            this.columnDropDown2.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.columnDropDown2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.columnDropDown2.ForeColor = System.Drawing.Color.Black;
            this.columnDropDown2.FormattingEnabled = true;
            this.columnDropDown2.Icon = null;
            this.columnDropDown2.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.columnDropDown2.IndicatorColor = System.Drawing.Color.DarkGray;
            this.columnDropDown2.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.columnDropDown2.IndicatorThickness = 2;
            this.columnDropDown2.IsDropdownOpened = false;
            this.columnDropDown2.ItemBackColor = System.Drawing.Color.White;
            this.columnDropDown2.ItemBorderColor = System.Drawing.Color.White;
            this.columnDropDown2.ItemForeColor = System.Drawing.Color.Black;
            this.columnDropDown2.ItemHeight = 26;
            this.columnDropDown2.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.columnDropDown2.ItemHighLightForeColor = System.Drawing.Color.White;
            this.columnDropDown2.ItemTopMargin = 3;
            this.columnDropDown2.Location = new System.Drawing.Point(12, 358);
            this.columnDropDown2.Name = "columnDropDown2";
            this.columnDropDown2.Size = new System.Drawing.Size(185, 32);
            this.columnDropDown2.TabIndex = 13;
            this.columnDropDown2.Text = null;
            this.columnDropDown2.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.columnDropDown2.TextLeftMargin = 5;
            // 
            // bunifuSeparator2
            // 
            this.bunifuSeparator2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator2.BackgroundImage")));
            this.bunifuSeparator2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator2.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator2.LineColor = System.Drawing.Color.Orange;
            this.bunifuSeparator2.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.bunifuSeparator2.LineThickness = 1;
            this.bunifuSeparator2.Location = new System.Drawing.Point(12, 387);
            this.bunifuSeparator2.Name = "bunifuSeparator2";
            this.bunifuSeparator2.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator2.Size = new System.Drawing.Size(185, 15);
            this.bunifuSeparator2.TabIndex = 14;
            // 
            // standardDeviationBtn
            // 
            this.standardDeviationBtn.AllowAnimations = true;
            this.standardDeviationBtn.AllowMouseEffects = true;
            this.standardDeviationBtn.AllowToggling = false;
            this.standardDeviationBtn.AnimationSpeed = 200;
            this.standardDeviationBtn.AutoGenerateColors = false;
            this.standardDeviationBtn.AutoRoundBorders = false;
            this.standardDeviationBtn.AutoSizeLeftIcon = true;
            this.standardDeviationBtn.AutoSizeRightIcon = true;
            this.standardDeviationBtn.BackColor = System.Drawing.Color.Transparent;
            this.standardDeviationBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.standardDeviationBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("standardDeviationBtn.BackgroundImage")));
            this.standardDeviationBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.standardDeviationBtn.ButtonText = "Standard deviation";
            this.standardDeviationBtn.ButtonTextMarginLeft = 0;
            this.standardDeviationBtn.ColorContrastOnClick = 45;
            this.standardDeviationBtn.ColorContrastOnHover = 45;
            this.standardDeviationBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.standardDeviationBtn.CustomizableEdges = borderEdges4;
            this.standardDeviationBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.standardDeviationBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.standardDeviationBtn.DisabledFillColor = System.Drawing.Color.Empty;
            this.standardDeviationBtn.DisabledForecolor = System.Drawing.Color.Empty;
            this.standardDeviationBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.standardDeviationBtn.Font = new System.Drawing.Font("Segoe UI Semibold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.standardDeviationBtn.ForeColor = System.Drawing.Color.White;
            this.standardDeviationBtn.IconLeft = null;
            this.standardDeviationBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.standardDeviationBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.standardDeviationBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.standardDeviationBtn.IconMarginLeft = 11;
            this.standardDeviationBtn.IconPadding = 10;
            this.standardDeviationBtn.IconRight = null;
            this.standardDeviationBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.standardDeviationBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.standardDeviationBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.standardDeviationBtn.IconSize = 25;
            this.standardDeviationBtn.IdleBorderColor = System.Drawing.Color.Empty;
            this.standardDeviationBtn.IdleBorderRadius = 0;
            this.standardDeviationBtn.IdleBorderThickness = 0;
            this.standardDeviationBtn.IdleFillColor = System.Drawing.Color.Empty;
            this.standardDeviationBtn.IdleIconLeftImage = null;
            this.standardDeviationBtn.IdleIconRightImage = null;
            this.standardDeviationBtn.IndicateFocus = false;
            this.standardDeviationBtn.Location = new System.Drawing.Point(12, 299);
            this.standardDeviationBtn.Name = "standardDeviationBtn";
            this.standardDeviationBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.standardDeviationBtn.OnDisabledState.BorderRadius = 1;
            this.standardDeviationBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.standardDeviationBtn.OnDisabledState.BorderThickness = 1;
            this.standardDeviationBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.standardDeviationBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.standardDeviationBtn.OnDisabledState.IconLeftImage = null;
            this.standardDeviationBtn.OnDisabledState.IconRightImage = null;
            this.standardDeviationBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.standardDeviationBtn.onHoverState.BorderRadius = 1;
            this.standardDeviationBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.standardDeviationBtn.onHoverState.BorderThickness = 1;
            this.standardDeviationBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.standardDeviationBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.standardDeviationBtn.onHoverState.IconLeftImage = null;
            this.standardDeviationBtn.onHoverState.IconRightImage = null;
            this.standardDeviationBtn.OnIdleState.BorderColor = System.Drawing.Color.Orange;
            this.standardDeviationBtn.OnIdleState.BorderRadius = 1;
            this.standardDeviationBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.standardDeviationBtn.OnIdleState.BorderThickness = 1;
            this.standardDeviationBtn.OnIdleState.FillColor = System.Drawing.Color.Orange;
            this.standardDeviationBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.standardDeviationBtn.OnIdleState.IconLeftImage = null;
            this.standardDeviationBtn.OnIdleState.IconRightImage = null;
            this.standardDeviationBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.standardDeviationBtn.OnPressedState.BorderRadius = 1;
            this.standardDeviationBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.standardDeviationBtn.OnPressedState.BorderThickness = 1;
            this.standardDeviationBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.standardDeviationBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.standardDeviationBtn.OnPressedState.IconLeftImage = null;
            this.standardDeviationBtn.OnPressedState.IconRightImage = null;
            this.standardDeviationBtn.Size = new System.Drawing.Size(185, 39);
            this.standardDeviationBtn.TabIndex = 12;
            this.standardDeviationBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.standardDeviationBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.standardDeviationBtn.TextMarginLeft = 0;
            this.standardDeviationBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.standardDeviationBtn.UseDefaultRadiusAndThickness = true;
            this.standardDeviationBtn.Click += new System.EventHandler(this.standardDeviationBtn_Click);
            // 
            // varianceBtn
            // 
            this.varianceBtn.AllowAnimations = true;
            this.varianceBtn.AllowMouseEffects = true;
            this.varianceBtn.AllowToggling = false;
            this.varianceBtn.AnimationSpeed = 200;
            this.varianceBtn.AutoGenerateColors = false;
            this.varianceBtn.AutoRoundBorders = false;
            this.varianceBtn.AutoSizeLeftIcon = true;
            this.varianceBtn.AutoSizeRightIcon = true;
            this.varianceBtn.BackColor = System.Drawing.Color.Transparent;
            this.varianceBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.varianceBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("varianceBtn.BackgroundImage")));
            this.varianceBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.varianceBtn.ButtonText = "Variance";
            this.varianceBtn.ButtonTextMarginLeft = 0;
            this.varianceBtn.ColorContrastOnClick = 45;
            this.varianceBtn.ColorContrastOnHover = 45;
            this.varianceBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.varianceBtn.CustomizableEdges = borderEdges5;
            this.varianceBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.varianceBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.varianceBtn.DisabledFillColor = System.Drawing.Color.Empty;
            this.varianceBtn.DisabledForecolor = System.Drawing.Color.Empty;
            this.varianceBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.varianceBtn.Font = new System.Drawing.Font("Segoe UI Semibold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.varianceBtn.ForeColor = System.Drawing.Color.White;
            this.varianceBtn.IconLeft = null;
            this.varianceBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.varianceBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.varianceBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.varianceBtn.IconMarginLeft = 11;
            this.varianceBtn.IconPadding = 10;
            this.varianceBtn.IconRight = null;
            this.varianceBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.varianceBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.varianceBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.varianceBtn.IconSize = 25;
            this.varianceBtn.IdleBorderColor = System.Drawing.Color.Empty;
            this.varianceBtn.IdleBorderRadius = 0;
            this.varianceBtn.IdleBorderThickness = 0;
            this.varianceBtn.IdleFillColor = System.Drawing.Color.Empty;
            this.varianceBtn.IdleIconLeftImage = null;
            this.varianceBtn.IdleIconRightImage = null;
            this.varianceBtn.IndicateFocus = false;
            this.varianceBtn.Location = new System.Drawing.Point(12, 254);
            this.varianceBtn.Name = "varianceBtn";
            this.varianceBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.varianceBtn.OnDisabledState.BorderRadius = 1;
            this.varianceBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.varianceBtn.OnDisabledState.BorderThickness = 1;
            this.varianceBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.varianceBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.varianceBtn.OnDisabledState.IconLeftImage = null;
            this.varianceBtn.OnDisabledState.IconRightImage = null;
            this.varianceBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.varianceBtn.onHoverState.BorderRadius = 1;
            this.varianceBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.varianceBtn.onHoverState.BorderThickness = 1;
            this.varianceBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.varianceBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.varianceBtn.onHoverState.IconLeftImage = null;
            this.varianceBtn.onHoverState.IconRightImage = null;
            this.varianceBtn.OnIdleState.BorderColor = System.Drawing.Color.Orange;
            this.varianceBtn.OnIdleState.BorderRadius = 1;
            this.varianceBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.varianceBtn.OnIdleState.BorderThickness = 1;
            this.varianceBtn.OnIdleState.FillColor = System.Drawing.Color.Orange;
            this.varianceBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.varianceBtn.OnIdleState.IconLeftImage = null;
            this.varianceBtn.OnIdleState.IconRightImage = null;
            this.varianceBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.varianceBtn.OnPressedState.BorderRadius = 1;
            this.varianceBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.varianceBtn.OnPressedState.BorderThickness = 1;
            this.varianceBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.varianceBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.varianceBtn.OnPressedState.IconLeftImage = null;
            this.varianceBtn.OnPressedState.IconRightImage = null;
            this.varianceBtn.Size = new System.Drawing.Size(185, 39);
            this.varianceBtn.TabIndex = 11;
            this.varianceBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.varianceBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.varianceBtn.TextMarginLeft = 0;
            this.varianceBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.varianceBtn.UseDefaultRadiusAndThickness = true;
            this.varianceBtn.Click += new System.EventHandler(this.varianceBtn_Click);
            // 
            // quantileButton
            // 
            this.quantileButton.AllowAnimations = true;
            this.quantileButton.AllowMouseEffects = true;
            this.quantileButton.AllowToggling = false;
            this.quantileButton.AnimationSpeed = 200;
            this.quantileButton.AutoGenerateColors = false;
            this.quantileButton.AutoRoundBorders = false;
            this.quantileButton.AutoSizeLeftIcon = true;
            this.quantileButton.AutoSizeRightIcon = true;
            this.quantileButton.BackColor = System.Drawing.Color.Transparent;
            this.quantileButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.quantileButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("quantileButton.BackgroundImage")));
            this.quantileButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.quantileButton.ButtonText = "Quantile";
            this.quantileButton.ButtonTextMarginLeft = 0;
            this.quantileButton.ColorContrastOnClick = 45;
            this.quantileButton.ColorContrastOnHover = 45;
            this.quantileButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.quantileButton.CustomizableEdges = borderEdges6;
            this.quantileButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.quantileButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.quantileButton.DisabledFillColor = System.Drawing.Color.Empty;
            this.quantileButton.DisabledForecolor = System.Drawing.Color.Empty;
            this.quantileButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.quantileButton.Font = new System.Drawing.Font("Segoe UI Semibold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.quantileButton.ForeColor = System.Drawing.Color.White;
            this.quantileButton.IconLeft = null;
            this.quantileButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.quantileButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.quantileButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.quantileButton.IconMarginLeft = 11;
            this.quantileButton.IconPadding = 10;
            this.quantileButton.IconRight = null;
            this.quantileButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.quantileButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.quantileButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.quantileButton.IconSize = 25;
            this.quantileButton.IdleBorderColor = System.Drawing.Color.Empty;
            this.quantileButton.IdleBorderRadius = 0;
            this.quantileButton.IdleBorderThickness = 0;
            this.quantileButton.IdleFillColor = System.Drawing.Color.Empty;
            this.quantileButton.IdleIconLeftImage = null;
            this.quantileButton.IdleIconRightImage = null;
            this.quantileButton.IndicateFocus = false;
            this.quantileButton.Location = new System.Drawing.Point(12, 209);
            this.quantileButton.Name = "quantileButton";
            this.quantileButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.quantileButton.OnDisabledState.BorderRadius = 1;
            this.quantileButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.quantileButton.OnDisabledState.BorderThickness = 1;
            this.quantileButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.quantileButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.quantileButton.OnDisabledState.IconLeftImage = null;
            this.quantileButton.OnDisabledState.IconRightImage = null;
            this.quantileButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.quantileButton.onHoverState.BorderRadius = 1;
            this.quantileButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.quantileButton.onHoverState.BorderThickness = 1;
            this.quantileButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.quantileButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.quantileButton.onHoverState.IconLeftImage = null;
            this.quantileButton.onHoverState.IconRightImage = null;
            this.quantileButton.OnIdleState.BorderColor = System.Drawing.Color.Orange;
            this.quantileButton.OnIdleState.BorderRadius = 1;
            this.quantileButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.quantileButton.OnIdleState.BorderThickness = 1;
            this.quantileButton.OnIdleState.FillColor = System.Drawing.Color.Orange;
            this.quantileButton.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.quantileButton.OnIdleState.IconLeftImage = null;
            this.quantileButton.OnIdleState.IconRightImage = null;
            this.quantileButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.quantileButton.OnPressedState.BorderRadius = 1;
            this.quantileButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.quantileButton.OnPressedState.BorderThickness = 1;
            this.quantileButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.quantileButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.quantileButton.OnPressedState.IconLeftImage = null;
            this.quantileButton.OnPressedState.IconRightImage = null;
            this.quantileButton.Size = new System.Drawing.Size(185, 39);
            this.quantileButton.TabIndex = 10;
            this.quantileButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.quantileButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.quantileButton.TextMarginLeft = 0;
            this.quantileButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.quantileButton.UseDefaultRadiusAndThickness = true;
            this.quantileButton.Click += new System.EventHandler(this.quantileButton_Click);
            // 
            // rangeButton
            // 
            this.rangeButton.AllowAnimations = true;
            this.rangeButton.AllowMouseEffects = true;
            this.rangeButton.AllowToggling = false;
            this.rangeButton.AnimationSpeed = 200;
            this.rangeButton.AutoGenerateColors = false;
            this.rangeButton.AutoRoundBorders = false;
            this.rangeButton.AutoSizeLeftIcon = true;
            this.rangeButton.AutoSizeRightIcon = true;
            this.rangeButton.BackColor = System.Drawing.Color.Transparent;
            this.rangeButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.rangeButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("rangeButton.BackgroundImage")));
            this.rangeButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.rangeButton.ButtonText = "Range of change";
            this.rangeButton.ButtonTextMarginLeft = 0;
            this.rangeButton.ColorContrastOnClick = 45;
            this.rangeButton.ColorContrastOnHover = 45;
            this.rangeButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.rangeButton.CustomizableEdges = borderEdges7;
            this.rangeButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.rangeButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.rangeButton.DisabledFillColor = System.Drawing.Color.Empty;
            this.rangeButton.DisabledForecolor = System.Drawing.Color.Empty;
            this.rangeButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.rangeButton.Font = new System.Drawing.Font("Segoe UI Semibold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.rangeButton.ForeColor = System.Drawing.Color.White;
            this.rangeButton.IconLeft = null;
            this.rangeButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.rangeButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.rangeButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.rangeButton.IconMarginLeft = 11;
            this.rangeButton.IconPadding = 10;
            this.rangeButton.IconRight = null;
            this.rangeButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.rangeButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.rangeButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.rangeButton.IconSize = 25;
            this.rangeButton.IdleBorderColor = System.Drawing.Color.Empty;
            this.rangeButton.IdleBorderRadius = 0;
            this.rangeButton.IdleBorderThickness = 0;
            this.rangeButton.IdleFillColor = System.Drawing.Color.Empty;
            this.rangeButton.IdleIconLeftImage = null;
            this.rangeButton.IdleIconRightImage = null;
            this.rangeButton.IndicateFocus = false;
            this.rangeButton.Location = new System.Drawing.Point(12, 164);
            this.rangeButton.Name = "rangeButton";
            this.rangeButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.rangeButton.OnDisabledState.BorderRadius = 1;
            this.rangeButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.rangeButton.OnDisabledState.BorderThickness = 1;
            this.rangeButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.rangeButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.rangeButton.OnDisabledState.IconLeftImage = null;
            this.rangeButton.OnDisabledState.IconRightImage = null;
            this.rangeButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.rangeButton.onHoverState.BorderRadius = 1;
            this.rangeButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.rangeButton.onHoverState.BorderThickness = 1;
            this.rangeButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.rangeButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.rangeButton.onHoverState.IconLeftImage = null;
            this.rangeButton.onHoverState.IconRightImage = null;
            this.rangeButton.OnIdleState.BorderColor = System.Drawing.Color.Orange;
            this.rangeButton.OnIdleState.BorderRadius = 1;
            this.rangeButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.rangeButton.OnIdleState.BorderThickness = 1;
            this.rangeButton.OnIdleState.FillColor = System.Drawing.Color.Orange;
            this.rangeButton.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.rangeButton.OnIdleState.IconLeftImage = null;
            this.rangeButton.OnIdleState.IconRightImage = null;
            this.rangeButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.rangeButton.OnPressedState.BorderRadius = 1;
            this.rangeButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.rangeButton.OnPressedState.BorderThickness = 1;
            this.rangeButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.rangeButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.rangeButton.OnPressedState.IconLeftImage = null;
            this.rangeButton.OnPressedState.IconRightImage = null;
            this.rangeButton.Size = new System.Drawing.Size(185, 39);
            this.rangeButton.TabIndex = 9;
            this.rangeButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.rangeButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.rangeButton.TextMarginLeft = 0;
            this.rangeButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.rangeButton.UseDefaultRadiusAndThickness = true;
            this.rangeButton.Click += new System.EventHandler(this.rangeButton_Click);
            // 
            // columnDropDown
            // 
            this.columnDropDown.BackColor = System.Drawing.Color.Transparent;
            this.columnDropDown.BackgroundColor = System.Drawing.Color.White;
            this.columnDropDown.BorderColor = System.Drawing.Color.Silver;
            this.columnDropDown.BorderRadius = 1;
            this.columnDropDown.Color = System.Drawing.Color.Silver;
            this.columnDropDown.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.columnDropDown.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.columnDropDown.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.columnDropDown.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.columnDropDown.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.columnDropDown.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.columnDropDown.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.columnDropDown.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.columnDropDown.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.columnDropDown.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.columnDropDown.FillDropDown = true;
            this.columnDropDown.FillIndicator = false;
            this.columnDropDown.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.columnDropDown.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.columnDropDown.ForeColor = System.Drawing.Color.Black;
            this.columnDropDown.FormattingEnabled = true;
            this.columnDropDown.Icon = null;
            this.columnDropDown.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.columnDropDown.IndicatorColor = System.Drawing.Color.DarkGray;
            this.columnDropDown.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.columnDropDown.IndicatorThickness = 2;
            this.columnDropDown.IsDropdownOpened = false;
            this.columnDropDown.ItemBackColor = System.Drawing.Color.White;
            this.columnDropDown.ItemBorderColor = System.Drawing.Color.White;
            this.columnDropDown.ItemForeColor = System.Drawing.Color.Black;
            this.columnDropDown.ItemHeight = 26;
            this.columnDropDown.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.columnDropDown.ItemHighLightForeColor = System.Drawing.Color.White;
            this.columnDropDown.ItemTopMargin = 3;
            this.columnDropDown.Location = new System.Drawing.Point(12, 69);
            this.columnDropDown.Name = "columnDropDown";
            this.columnDropDown.Size = new System.Drawing.Size(185, 32);
            this.columnDropDown.TabIndex = 6;
            this.columnDropDown.Text = null;
            this.columnDropDown.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.columnDropDown.TextLeftMargin = 5;
            // 
            // bunifuSeparator1
            // 
            this.bunifuSeparator1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator1.BackgroundImage")));
            this.bunifuSeparator1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator1.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator1.LineColor = System.Drawing.Color.Orange;
            this.bunifuSeparator1.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.bunifuSeparator1.LineThickness = 1;
            this.bunifuSeparator1.Location = new System.Drawing.Point(12, 98);
            this.bunifuSeparator1.Name = "bunifuSeparator1";
            this.bunifuSeparator1.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator1.Size = new System.Drawing.Size(185, 15);
            this.bunifuSeparator1.TabIndex = 8;
            // 
            // avrageButton
            // 
            this.avrageButton.AllowAnimations = true;
            this.avrageButton.AllowMouseEffects = true;
            this.avrageButton.AllowToggling = false;
            this.avrageButton.AnimationSpeed = 200;
            this.avrageButton.AutoGenerateColors = false;
            this.avrageButton.AutoRoundBorders = false;
            this.avrageButton.AutoSizeLeftIcon = true;
            this.avrageButton.AutoSizeRightIcon = true;
            this.avrageButton.BackColor = System.Drawing.Color.Transparent;
            this.avrageButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.avrageButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("avrageButton.BackgroundImage")));
            this.avrageButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.avrageButton.ButtonText = "Avrage";
            this.avrageButton.ButtonTextMarginLeft = 0;
            this.avrageButton.ColorContrastOnClick = 45;
            this.avrageButton.ColorContrastOnHover = 45;
            this.avrageButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.avrageButton.CustomizableEdges = borderEdges8;
            this.avrageButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.avrageButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.avrageButton.DisabledFillColor = System.Drawing.Color.Empty;
            this.avrageButton.DisabledForecolor = System.Drawing.Color.Empty;
            this.avrageButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.avrageButton.Font = new System.Drawing.Font("Segoe UI Semibold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.avrageButton.ForeColor = System.Drawing.Color.White;
            this.avrageButton.IconLeft = null;
            this.avrageButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.avrageButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.avrageButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.avrageButton.IconMarginLeft = 11;
            this.avrageButton.IconPadding = 10;
            this.avrageButton.IconRight = null;
            this.avrageButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.avrageButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.avrageButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.avrageButton.IconSize = 25;
            this.avrageButton.IdleBorderColor = System.Drawing.Color.Empty;
            this.avrageButton.IdleBorderRadius = 0;
            this.avrageButton.IdleBorderThickness = 0;
            this.avrageButton.IdleFillColor = System.Drawing.Color.Empty;
            this.avrageButton.IdleIconLeftImage = null;
            this.avrageButton.IdleIconRightImage = null;
            this.avrageButton.IndicateFocus = false;
            this.avrageButton.Location = new System.Drawing.Point(12, 119);
            this.avrageButton.Name = "avrageButton";
            this.avrageButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.avrageButton.OnDisabledState.BorderRadius = 1;
            this.avrageButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.avrageButton.OnDisabledState.BorderThickness = 1;
            this.avrageButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.avrageButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.avrageButton.OnDisabledState.IconLeftImage = null;
            this.avrageButton.OnDisabledState.IconRightImage = null;
            this.avrageButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.avrageButton.onHoverState.BorderRadius = 1;
            this.avrageButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.avrageButton.onHoverState.BorderThickness = 1;
            this.avrageButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.avrageButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.avrageButton.onHoverState.IconLeftImage = null;
            this.avrageButton.onHoverState.IconRightImage = null;
            this.avrageButton.OnIdleState.BorderColor = System.Drawing.Color.Orange;
            this.avrageButton.OnIdleState.BorderRadius = 1;
            this.avrageButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.avrageButton.OnIdleState.BorderThickness = 1;
            this.avrageButton.OnIdleState.FillColor = System.Drawing.Color.Orange;
            this.avrageButton.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.avrageButton.OnIdleState.IconLeftImage = null;
            this.avrageButton.OnIdleState.IconRightImage = null;
            this.avrageButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.avrageButton.OnPressedState.BorderRadius = 1;
            this.avrageButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.avrageButton.OnPressedState.BorderThickness = 1;
            this.avrageButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.avrageButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.avrageButton.OnPressedState.IconLeftImage = null;
            this.avrageButton.OnPressedState.IconRightImage = null;
            this.avrageButton.Size = new System.Drawing.Size(185, 39);
            this.avrageButton.TabIndex = 7;
            this.avrageButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.avrageButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.avrageButton.TextMarginLeft = 0;
            this.avrageButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.avrageButton.UseDefaultRadiusAndThickness = true;
            this.avrageButton.Click += new System.EventHandler(this.avrageButton_Click);
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.Orange;
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BorderRadius = 3;
            this.bunifuPanel2.BorderThickness = 1;
            this.bunifuPanel2.Controls.Add(this.bunifuButton1);
            this.bunifuPanel2.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.ShowBorders = true;
            this.bunifuPanel2.Size = new System.Drawing.Size(208, 63);
            this.bunifuPanel2.TabIndex = 0;
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1228, 715);
            this.Controls.Add(this.bunifuPanel1);
            this.Controls.Add(this.dataGridView);
            this.ForeColor = System.Drawing.Color.Black;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.Name = "Form1";
            this.Text = "Data mining";
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView)).EndInit();
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel2.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuDataGridView dataGridView;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton avrageButton;
        private Bunifu.UI.WinForms.BunifuDropdown columnDropDown;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton rangeButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton quantileButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton varianceBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton standardDeviationBtn;
        private Bunifu.UI.WinForms.BunifuDropdown columnDropDown2;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton covButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton correlationCoefficientBtn;
    }
}

